let gotypes = {
    Body: "*hype.Body",
    Cmd: "*hype.Cmd",
    CmdError: "hype.CmdError",
    CmdResult: "*hype.CmdResult",
    Element: "*hype.Element",
    ExecuteError: "hype.ExecuteError",
    FencedCode: "*hype.FencedCode",
    Figcaption: "*hype.Figcaption",
    Figure: "*hype.Figure",
    Heading: "hype.Heading",
    HypeError: "hype.HypeError",
    Image: "*hype.Image",
    Include: "*hype.Include",
    InlineCode: "*hype.InlineCode",
    LI: "*hype.LI",
    Link: "*hype.Link",
    OL: "*hype.OL",
    Page: "*hype.Page",
    Paragraph: "*hype.Paragraph",
    ParseError: "hype.ParseError",
    Ref: "*hype.Ref",
    RunError: "clam.RunError",
    Snippet: "hype.Snippet",
    SourceCode: "*hype.SourceCode",
    TD: "*hype.TD",
    TH: "*hype.TH",
    THead: "*hype.THead",
    TR: "*hype.TR",
    Table: "*hype.Table",
    Text: "hype.Text",
    UL: "*hype.UL",
}

export { gotypes }